mode: train
lmdb: false
dry_run: false
rgb_dir: '../train_crop'
lmdb_dir:  ''
dataset_json_folder: "../dataset_json"
SWA: False
save_avg: True
log_dir: ./exps
# label settings
label_dict:
  # DFD
  DFD_fake: 1
  DFD_real: 0
 